spring.application.name=demo

#spring.data.mongodb.uri=mongodb://localhost:27017/productdb


jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u

server.port=8080

logging.level.org.springframework.data.mongodb=DEBUG

logging.level.com.userProductInfo=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.level.org.springframework.transaction=TRACE


google.oauth.client-id=192879090821-510fkj1ue3mhhi4bv7vtvp5u9glh5oo2.apps.googleusercontent.com

google.oauth.client-secret=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