spring.application.name=demo

#spring.data.mongodb.uri=mongodb://localhost:27017/productdb


jwt.secret=${JWT_SECRET}

server.port=8080

logging.level.org.springframework.data.mongodb=DEBUG

logging.level.com.userProductInfo=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

logging.level.org.springframework.transaction=TRACE


google.oauth.client-id=${GOOGLE_CLIENT_ID}

google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}